[build]
  # we're doing rm -rf node_modules because otherwise things are broken
  command = "rm -rf node_modules && yarn && yarn website build"
  publish = "website/public"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.19.0"
  YARN_FLAGS = "--frozen-lockfile"
