packages:
  - 'docs'
  - 'examples/**'
  - 'packages/*'
  - 'tests/admin-ui-tests'
  - 'tests/api-tests'
  - 'tests/benchmarks'
  - 'tests/examples-smoke-tests'
  - 'tests/test-projects/*'
  - 'tests/sandbox'
  - 'tests/cli-tests'
  - 'tests2/'
  - 'prisma-utils'
  - '!**/node_modules/**'
catalog:
  '@prisma/client': ^6.19.3
  '@prisma/client-generator-registry': ^6.19.3
  '@prisma/engines': ^6.19.3
  '@prisma/generator-helper': ^6.19.3
  '@prisma/internals': ^6.19.3
  '@prisma/migrate': ^6.19.3
  '@types/express': ^4.17.14
  '@types/node': ^24.0.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  express: ^4.19.2
  graphql: ^16.8.1
  next: ^16.2.10
  prisma: ^6.19.3
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^6.0.0
  '@keystar/ui': 0.8.0
  react-aria: 3.50.0
  react-stately: 3.48.0
allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  deasync: false
  esbuild: true
  prisma: true
  sharp: false
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - '@keystar/ui'
  - '@keystatic/core'
