catalog:
  '@types/babel__core': ^7.20.5
  "@types/express": ^4.17.14
  '@types/node': ^20.14.10
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  #'@babel/runtime': ^7.24.7 # TODO: breaks preconstruct for now
  'esbuild': ^0.23.0
  'express': ^4.19.2
  'graphql': ^16.8.1
  'next': ^14.2.0
  'prisma': 5.16.1
  '@prisma/client': 5.16.1
  'react': ^18.3.1
  'react-dom': ^18.3.1
  'tsx': ^4.0.0
  'typescript': ^5.5.0

packages:
  - 'design-system/packages/*'
  - 'design-system/website'
  - 'docs'
  - 'examples/**'
  - 'packages/*'
  - 'tests/admin-ui-tests'
  - 'tests/api-tests'
  - 'tests/benchmarks'
  - 'tests/examples-smoke-tests'
  - 'tests/test-projects/*'
  - 'tests/sandbox'
  - 'tests/cli-tests'
  - 'prisma-utils'
  - '!**/node_modules/**'
