packages:
  - 'design-system/packages/*'
  - 'design-system/website'
  - 'docs'
  - 'examples/**'
  - 'packages/*'
  - 'tests/admin-ui-tests'
  - 'tests/api-tests'
  - 'tests/benchmarks'
  - 'tests/examples-smoke-tests'
  - 'tests/test-projects/*'
  - 'tests/sandbox'
  - 'tests/cli-tests'
  - 'prisma-utils'
  - '!**/node_modules/**'
