name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash
    - name: Setup Node.js LTS
      uses: actions/setup-node@v3
      with:
        # preferably lts/*, but we hit API limits when querying that
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
