name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@main
      with:
        # preferably lts/*, but we hit API limits when querying that
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - run: rm --recursive --force examples/ tests/test-projects/
      shell: bash

    - run: pnpm install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

    - run: pnpm run build
      shell: bash
