name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@main
      with:
        # preferably lts/*, but we hit API limits when querying that
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'

    - run: yarn --frozen-lockfile
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
