// flow-typed signature: a54fc8586202adf721313159338eb62e
// flow-typed version: <<STUB>>/@emotion/styled-base_v10.0.14/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/styled-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/styled-base' {
  declare module.exports: any;
}
