// flow-typed signature: a54fc8586202adf721313159338eb62e
// flow-typed version: <<STUB>>/@emotion/styled-base_v10.0.14/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/styled-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/styled-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/styled-base/dist/styled-base.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/dist/styled-base.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/dist/styled-base.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/dist/styled-base.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/dist/styled-base.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/dist/styled-base.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/dist/styled-base.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/src' {
  declare module.exports: any;
}

declare module '@emotion/styled-base/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/styled-base/dist/styled-base.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.browser.cjs'>;
}
declare module '@emotion/styled-base/dist/styled-base.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.browser.esm'>;
}
declare module '@emotion/styled-base/dist/styled-base.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.cjs.dev'>;
}
declare module '@emotion/styled-base/dist/styled-base.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.cjs'>;
}
declare module '@emotion/styled-base/dist/styled-base.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.cjs.prod'>;
}
declare module '@emotion/styled-base/dist/styled-base.esm.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.esm'>;
}
declare module '@emotion/styled-base/dist/styled-base.umd.min.js' {
  declare module.exports: $Exports<'@emotion/styled-base/dist/styled-base.umd.min'>;
}
declare module '@emotion/styled-base/src/index' {
  declare module.exports: $Exports<'@emotion/styled-base/src'>;
}
declare module '@emotion/styled-base/src/index.js' {
  declare module.exports: $Exports<'@emotion/styled-base/src'>;
}
declare module '@emotion/styled-base/src/utils.js' {
  declare module.exports: $Exports<'@emotion/styled-base/src/utils'>;
}
