// flow-typed signature: c0a247c13aec79d77053b130b7a57ff6
// flow-typed version: <<STUB>>/fixturez_v1.1.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fixturez'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fixturez' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fixturez/index' {
  declare module.exports: $Exports<'fixturez'>;
}
declare module 'fixturez/index.js' {
  declare module.exports: $Exports<'fixturez'>;
}
