// flow-typed signature: 20f8b4c4028b99548ab738c9bff6ef55
// flow-typed version: <<STUB>>/globby_v8.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globby' {
  declare module.exports: {
    (globs: string | Array<string>, options: Object): Promise<Array<string>>,
    sync: (globs: string | Array<string>, options: Object) => Array<string>,
  };
}
