// flow-typed signature: 375bd9e884de49de21ffed99c7e577dc
// flow-typed version: <<STUB>>/p-limit_v1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "p-limit" {
  declare module.exports: (
    concurrency: number
  ) => <V, Args>(
    func: (...args: Args) => Promise<V>,
    ...args: Args
  ) => Promise<V>;
}
