module.exports = {
  Integer: require('@voussoir/field-integer'),
  Password: require('@voussoir/field-password'),
  Text: require('@voussoir/field-text'),
  Float: require('@voussoir/field-float'),
  Checkbox: require('@voussoir/field-checkbox'),
  Select: require('@voussoir/field-select'),
  Relationship: require('@voussoir/field-relationship'),
  File: require('@voussoir/field-file'),
  CloudinaryImage: require('@voussoir/field-cloudinary-image'),
  CalendarDay: require('@voussoir/field-calendar-day'),
  DateTime: require('@voussoir/field-date-time'),
  Decimal: require('@voussoir/field-decimal'),
  Color: require('@voussoir/field-color'),
  Url: require('@voussoir/field-url'),
  Content: require('@voussoir/field-content'),
};
