module.exports = {
  Implementation: require('./Implementation'),
  Integer: require('./types/Integer'),
  Password: require('./types/Password'),
  Text: require('./types/Text'),
  Float: require('./types/Float'),
  Checkbox: require('./types/Checkbox'),
  Select: require('./types/Select'),
  Relationship: require('./types/Relationship'),
  File: require('./types/File'),
  CloudinaryImage: require('./types/CloudinaryImage'),
  CalendarDay: require('./types/CalendarDay'),
  DateTime: require('./types/DateTime'),
  Decimal: require('./types/Decimal'),
};
