name: 'CI setup (w/ examples)'
runs:
  using: 'composite'
  steps:
    - run: npm i -g corepack@0.31.0
      shell: bash
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@main
      with:
        # preferably lts/*, but we hit API limits when querying that
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
    - run: |
        find examples tests -name 'package.json' -exec sh -c '
          jq ".scripts |= if has(\"postinstall\") then . + {\"ks-examples-postinstall\": .postinstall} | del(.postinstall) else . end" "$1" > tmp && mv tmp "$1"
        ' sh {} \;
      shell: bash

    # limited to 1 child process, preventing Prisma postinstall races in our examples
    - run: pnpm install --child-concurrency 1
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

    - run: pnpm run build
      shell: bash
