name: 'CI setup (w/ examples)'
runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@main
      with:
        # preferably lts/*, but we hit API limits when querying that
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    # limited to 1 child process, preventing Prisma postinstall races in our examples
    - run: pnpm install --child-concurrency 1
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

    - run: pnpm run build
      shell: bash
