name: 'CI setup (w/ examples)'
runs:
  using: 'composite'
  steps:
    - run: npm i -g corepack@0.31.0
      shell: bash
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@main
      with:
        # preferably lts/*, but we hit API limits when querying that
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
    - run: |
        find examples tests -name 'package.json' -exec sh -c '
          jq "del(.scripts.postinstall)" "$1" > tmp && mv tmp "$1"
        ' sh {} \;
      shell: bash
      if: inputs.run-example-postinstall == false

    # limited to 1 child process, preventing Prisma postinstall races in our examples
    - run: pnpm install --child-concurrency 1
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

    - run: pnpm run build
      shell: bash

inputs:
  run-examples-postinstall:
    required: false
    default: false
