name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: always-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/ci-setup

      - name: Prettier
        run: yarn lint:prettier

      - name: TypeScript
        run: yarn lint:types

      - name: ESLint
        run: yarn lint:eslint

      - name: Preconstruct
        run: yarn build

      - name: Prisma Filters
        run: yarn lint:filters

  unit_tests:
    name: Package Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/ci-setup

      - name: Unit tests
        run: yarn jest --ci --runInBand --testPathIgnorePatterns=admin-ui-tests --testPathIgnorePatterns=api-tests --testPathIgnorePatterns=examples-smoke-tests --testPathIgnorePatterns=examples/testing
