name: Create Release PR

on:
  push:
    branches:
      - main

jobs:
  release_pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/ci-setup

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn version-packages
        env:
          # note that we're not using the GH token provided by Actions here because Actions has a rule that Actions
          # will not run as the result of another Action so CI wouldn't run on the release PRs then
          # we can get around it by using a personal access token from a GH account
          GITHUB_TOKEN: ${{ secrets.KEYSTONE_RELEASE_BOT_GITHUB_TOKEN }}
