name: Publish Snapshot Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The npm tag to publish to'
        required: true

jobs:
  publish_snapshot_release:
    name: Publish Snapshot Release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: true # needed for git push

      - uses: ./.github/actions/ci-setup

      - name: version packages
        run: yarn changeset version --snapshot ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.KEYSTONE_RELEASE_BOT_GITHUB_TOKEN }}

      - name: git commit
        run: |
          git config --global user.name 'Keystonejs Release Bot'
          git config --global user.email 'github@keystonejs.com'
          git commit -a -m 'rc'

      - name: npm publish, git tag
        run: yarn build && yarn changeset publish --tag ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # reset, then push the dangling commit
      - name: git push
        run: |
          git reset HEAD~1 --hard
          git push origin --tags-only
