name: CI - Windows

on:
  workflow_dispatch:

concurrency:
  group: ci-tests-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: Package Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/ci-setup

      - name: Unit tests
        run: pnpm vitest run --maxWorkers=1 --exclude='tests/admin-ui-tests/**' --exclude='tests/api-tests/**' --exclude='tests/examples-smoke-tests/**'
