name: Vercel (Preview)

on:
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Vercel
      url: ${{ steps.deploy.outputs.url }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@main

      - run: corepack enable

      - uses: actions/setup-node@main
        with:
          # preferably lts/*, but we hit API limits when querying that
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - run: pnpm install -w vercel@canary

      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - id: deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> "$GITHUB_OUTPUT"
