name: Vercel - Preview

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: vercel
    steps:
      - uses: actions/checkout@main
      
      - run: npm install --global vercel@canary
      
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
