name: Version Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  versioning:
    name: Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - uses: ./.github/actions/ci-setup

      - name: Add back examples
        run: git checkout -- examples tests/test-projects

      - uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          version: pnpm ci:version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
